pollster/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/details/', views.details, name='details'),
]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

pollster/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200, default='')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollster/polls/views.py
from django.http.response import Http404
from django.shortcuts import render

from .models import Question, Choice

# Get questions and display them


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def details(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist')        
        
    return render(request, 'polls/details.html', {'question': question})

pollster/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />
    <title>Pollster {% block title %} {% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-4 mx-auto"></div>
        {% block content %} {% endblock %}
      </div>
    </div>

    <script src="" async defer></script>
  </body>
</html>

pollster/templates/polls/details.html
{% extends 'base.html' %} 

{% block content %}

<h1 class="text-center mb-3">Question Details</h1>

{% if question %}


<div class="card mb-3">
      <div class='card-body'>
            <p class='lead'>
                {{question.question_text}}
            </p>
      </div>
</div>

{% else %}
<p>No question available</p>
{% endif %}
{% endblock %}

pollster/templates/polls/index.html
{% extends 'base.html' %} 

{% block content %}

<h1 class="text-center mb-3">Poll Questions</h1>

    {% if latest_question_list %} 

      {% for question in latest_question_list %}
<div class="card mb-3">
  <div class="card-body">
    <p class="lead">{{question.question_text}}</p>
    <a href="{% url 'polls:details' question.id %}" class="btn btn-primary">
      Details
    </a>
  </div>
</div>
    {% endfor %} 
    {% else %}
<p>No polls available</p>
    {% endif %} 
{% endblock %}